### ISSUE TITLE
Optional setting Allowed Environments is not optional

### ISSUE THREAD

**Issue by simpadat** [strebbor/Seq.App.Exporter#1]
Hi,
When I first installed this app in my Seq instance I could only get exceptions.
``System.Exception: App is not allowed to run for this event.``

It wasn't until I looked at the github code that I found this error message means that the event was failing the IsEnvironmentAllowed check.
After I specified an environment variable the app then forwarded the event details to my endpoint.

Thanks.

**Comment by strebbor** [comment]
Thank you very much for picking up this bug.  
I have fixed it and uploaded a new package in Nuget and in GitHub.
The IsEnvironmentAllowed check should now run even when the setting is blank.
